### ISSUE TITLE
Error in rule preprocess - FastQC after Sortmerna

### ISSUE THREAD

**Issue by ChrisTrivedi** [iquasere/MOSCA#17] opened 2022-01-17 15:19 UTC
Dear MOSCA Devs,

My apologies for creating a new issue, however, I added a comment to the old issue and am now realizing that there may be no notifications on closed issues. I'm reposting my issue here with a link to the comment. If this is improper procedure please let me know and I can delete this issue.

----------

I'm testing the latest release of MOSCA! Unfortunately, though, I'm already hindered by another preprocess error.

Somehow I'm getting stuck on a FastQC step after rRNA removal using Sortmerna. I believe it's because the `after_rrna_removal_*` files are empty - or at least they are 0 kb on inspection. I haven't been able to determine why this is though.

Here is the full error, maybe you can track it better than I can? Thanks!

```
FastQC --threads 16 --extract /home/ctrivedi/Working/Deep_Purple/mosca_GR19/output/Preprocess/SortMeRNA/after_rrna_removal_GRIS1_TR_forward.fastq /home/ctrivedi/Working/Deep_Purple/mosca_GR19/output/Preprocess/SortMeRNA/after_rrna_removal_GRIS1_TR_reverse.fastq
Started analysis of after_rrna_removal_GRIS1_TR_forward.fastq
Analysis complete for after_rrna_removal_GRIS1_TR_forward.fastq
Failed to process file after_rrna_removal_GRIS1_TR_forward.fastq
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(SequenceLengthDistribution.java:190)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Started analysis of after_rrna_removal_GRIS1_TR_reverse.fastq
Analysis complete for after_rrna_removal_GRIS1_TR_reverse.fastq
Failed to process file after_rrna_removal_GRIS1_TR_reverse.fastq
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
        at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(SequenceLengthDistribution.java:190)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Traceback (most recent call last):
  File "/home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/preprocess.py", line 357, in <module>
    Preprocesser().run()
  File "/home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/preprocess.py", line 343, in run
    minlen=args.minlen, type_of_data=args.data)
  File "/home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/preprocess.py", line 248, in quality_trimming
    data = parse_fastqc_report(report)
  File "/home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/mosca_tools.py", line 249, in parse_fastqc_report
    file = open(filename).read().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ctrivedi/Working/Deep_Purple/mosca_GR19/output/Preprocess/FastQC/after_rrna_removal_GRIS1_TR_forward_fastqc/fastqc_data.txt'
[Thu Jan 13 16:39:23 2022]
Error in rule preprocess:
    jobid: 0
    output: /home/ctrivedi/Working/Deep_Purple/mosca_GR19/output/Preprocess/Trimmomatic/quality_trimmed_GRIS1_TR_forward_paired.fq, /home/ctrivedi/Working/Deep_Purple/mosca_GR19/output/Preprocess/Trimmomatic/quality_trimmed_GRIS1_TR_reverse_paired.fq

RuleException:
CalledProcessError in line 103 of /home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/Snakefile:
Command 'set -euo pipefail;  python /home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/preprocess.py -i /home/ctrivedi/Working/Deep_Purple/GR19_Metatranscriptomes/Raw/totalRNA/RNA_TR_zymo7_S4_R1_001.fastq.gz,/home/ctrivedi/Working/Deep_Purple/GR19_Metatranscriptomes/Raw/totalRNA/RNA_TR_zymo7_S4_R2_001.fastq.gz -t 16 -o /home/ctrivedi/Working/Deep_Purple/mosca_GR19/output/Preprocess -adaptdir resources_directory/adapters -rrnadbs resources_directory/rRNA_databases -d mrna -rd resources_directory -n GRIS1_TR --minlen 100 --avgqual 20' returned non-zero exit status 1.
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2347, in run_wrapper
  File "/home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/Snakefile", line 103, in __rule_preprocess
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2359, in run_wrapper
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ctrivedi/Working/Deep_Purple/mosca_GR19/.snakemake/log/2022-01-13T163802.188280.snakemake.log
```

_Originally posted by @ChrisTrivedi in https://github.com/iquasere/MOSCA/issues/15#issuecomment-1012278807_

**Comment by iquasere** [comment] 2022-01-19 14:41
Sorry for not paying attention to this yet, but I am currently finishing a publication. Next week I will be able to look into this. However, it is strange that the preprocessing fails, since MOSCA is working fine in my local tests, and in the [repo's CI](https://github.com/iquasere/MOSCA/runs/3220046733?check_suite_focus=true). 

If you are getting 0Kb files after SortMeRNA, it must be something to do with the commands MOSCA uses to remove orphans that are left by SortMeRNA... and it would make sense, if your data does not follow the standard that MOSCA was programmed to use. Could you please show me the result of a ```head``` on the data causing this? And, if possible, a subset of the data that reproduces this error. Probably the first 1000 lines of your data would be enough to reproduce it.

**Comment by ChrisTrivedi** [comment] 2022-01-24 12:57
No worries at all, I appreciate your reply - and I understand when you're working on a paper submission it becomes all-consuming of your time!

I will get back to this over the next few days and update my reply with what I find. Thanks!

**Comment by iquasere** [comment] 2022-02-01 11:42
@ChrisTrivedi , I will be working on finishing MOSCA 2.0 (version with metaproteomics workflow completely functional) in the next few weeks so it will be a good time to tackle this issue :)

**Comment by ChrisTrivedi** [comment] 2022-02-01 15:10
@iquasere 
Okay, I'm back on the grind. Somehow I've gotten past the sortmerna issue, it could have been a version problem. However, now I've run into a new issue during assembly:

```
python /home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/assembly.py -r output/Preproce ss/MIT2_forward.fastq,output/Preprocess/MIT2_reverse.fastq,output/Preprocess/MIT1_forward.fast q,output/Preprocess/MIT1_reverse.fastq -t 24 -o output/Assembly/MIT2 MIT1 -a metaspades -m 64
usage: assembly.py [-h] -r READS [-o OUTPUT] [-t THREADS]
                   [-a {metaspades,megahit,rnaspades}] [-m MEMORY]
                   [-rl READ_LENGTH] [-is INSERT_SIZE] [-stdi STD_INSERT]
                   [-bq {phred33,phred64}] [-mrn MAX_REF_NUMBER]
assembly.py: error: unrecognized arguments: MIT1
[Tue Feb  1 15:11:35 2022]
Error in rule assembly:
    jobid: 0
    output: output/Assembly/MIT2/contigs.fasta, output/Assembly/MIT1/contigs.fasta, output/Assembly/MIT2/scaffolds.fasta, output/Assembly/MIT1/scaffolds.fasta

RuleException:
CalledProcessError in line 139 of /home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/Snakefile:
Command 'set -euo pipefail;  python /home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/assembly.py -r output/Preprocess/MIT2_forward.fastq,output/Preprocess/MIT2_reverse.fastq,output /Preprocess/MIT1_forward.fastq,output/Preprocess/MIT1_reverse.fastq -t 24 -o output/Assembly/MIT2 MIT1 -a metaspades -m 64' returned non-zero exit status 2.
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/_ _init__.py", line 2347, in run_wrapper
  File "/home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/Snakefile", line 139, in __rule_assembly
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/_ _init__.py", line 568, in _callback
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/concurrent/futures/thread.py", line  57, in run
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/_ _init__.py", line 554, in cached_or_run
  File "/home/ctrivedi/miniconda3/envs/mosca/lib/python3.7/site-packages/snakemake/executors/_ _init__.py", line 2359, in run_wrapper
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ctrivedi/Mosca/.snakemake/log/2022-02-01T144821.572791.snakemake.log
```

From what I can tell, it has to do with the name of the output assembly file, where it thinks the second sample name `MIT1` is a flag: `-o output/Assembly/MIT2 MIT1 -a metaspades -m 64' returned non-zero exit status 2.` It may just be how the pipeline assigns the final co-assembly name based on your code in `assembly.py`, but I don't know enough about python to fix it. For reference, I'm only working with two samples (MIT1 and MIT2) at the moment (each with a MT and MG), just to test the pipeline before I add more to the workflow.

Also, another random error I get is when activating MOSCA: 
```
ctrivedi ~/Mosca $ conda activate mosca
ERROR: This cross-compiler package contains no program /home/ctrivedi/miniconda3/envs/mosca/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: activate-gfortran_linux-64.sh made the following environmental changes:
+HOST=x86_64-conda_cos6-linux-gnu
-HOST=x86_64-conda-linux-gnu
```

It doesn't seem to have impacted my use of MOSCA yet, but I thought I would bring it up anyway.

> @ChrisTrivedi , I will be working on finishing MOSCA 2.0 (version with metaproteomics workflow completely functional) in the next few weeks so it will be a good time to tackle this issue :)

This is music to my ears as we will also be incorporating metaproteomics as part of our dataset within the next year. Very cool!

I hope the manuscript submission is going well and as always thanks for any help! 🙂

**Comment by iquasere** [comment] 2022-02-01 16:16
This command 
```
python /home/ctrivedi/miniconda3/envs/mosca/share/MOSCA/scripts/assembly.py -r output/Preproce ss/MIT2_forward.fastq,output/Preprocess/MIT2_reverse.fastq,output/Preprocess/MIT1_forward.fast q,output/Preprocess/MIT1_reverse.fastq -t 24 -o output/Assembly/MIT2 MIT1 -a metaspades -m 64
```
presents a lot of brakes, specifically at ```Preproce ss/MIT2```, ```forward.fast q,output``` and at the referenced ```Assembly/MIT2 MIT1```. I have never seen MOSCA do such a thing... To know what may be happening here, I would need the config and experiments files that make this error happen, as well as the input datasets. Are you obtaining your config and experiments files from [MOSGUITO](https://iquasere.github.io/MOSGUITO/)? Or are you running parts separately, as explained in the [wiki](https://github.com/iquasere/MOSCA/wiki/Partial-runs)?

About the error you get from activating MOSCA, this always happens to me as well, seems to be due to some tool using Fortran, but it has no impact on the functionality of MOSCA. It seems to solve itself every time it is reported.

Finally, thank you for the kind words :) Lets just see if this tool can be of any help for your work

**Comment by ChrisTrivedi** [comment] 2022-02-01 16:57
Hmmm, it could be the breaks were introduced when I copied over from the terminal? I've since restarted the pipeline with just one sample (MIT1) to test if it was a co-assembly problem, and I am already up to the point of `annotation`, so past the initial assembly part at least.

I did not use MOSGUITO and I'm attempting to run the entire pipeline and not separate parts. I'm happy to send my config, experiments, and raw data file your way. Could this be accomplished via email? Thanks!

**Comment by iquasere** [comment] 2022-02-01 17:26
Yes, you can send the files to maildosequeira@gmail.com! I will test on my end, and see if I can reproduce the error in my system.

**Comment by ChrisTrivedi** [comment] 2022-02-02 16:19
Here is my most recent error. I'm not sure if it has to do with the `resources_directory/COG_20_0.aux not found!` error or the lower down `OSError: [Errno 24] Too many open files`. Apologies for the screenshot, I'm using `tmux` and realizing it's not so easy to copy to the system clipboard.

![image](https://user-images.githubusercontent.com/13127554/152193060-5c4a84a6-1c45-4507-8975-4bdba999332c.png)

**Comment by iquasere** [comment] 2022-05-24 10:24
After 5 months, I believe this error has been fixed. Next weeks will see new versions of MOSCA, driven to validate its MP workflow, please if the interest is still there for MOSCA, do experiment with this new version (1.6).

I will now experiment with the files you have sent me (finally!), if they do not produce any error I will inform you and close this issue. Thank you again for reporting on this!

**Comment by ChrisTrivedi** [comment] 2022-06-15 17:03
> After 5 months, I believe this error has been fixed. Next weeks will see new versions of MOSCA, driven to validate its MP workflow, please if the interest is still there for MOSCA, do experiment with this new version (1.6).
> 
> I will now experiment with the files you have sent me (finally!), if they do not produce any error I will inform you and close this issue. Thank you again for reporting on this!

Hey, @iquasere , exciting to see new versions of MOSCA coming out. I will make sure to carve out some time to test this on my end as well. Thank you for following up after all this time!

**Closed as completed** 2022-09-23 09:04 UTC
